### PR TITLE
Add ESLint, with Airbnb style guide, and Prettier

### PR DESCRIPTION
**Pull request by 8thDay**
Installs ESLint in the project root, using Airbnb style guide.
Disables any code formatting rules which would conflict with Prettier's rule set.

ESLint will be run when the dev script is invoked.
The project root and the client/src directory are currently included in the linting process.
Errors and warnings will be written to the console.
If errors are present, the dev environment will not start.

ESLint can be invoked manually, using the commands `npm run lint:client` and `npm run lint:server`

Runs Prettier on a precommit hook. 
It will re-write staged files, in order to enforce style formatting standards.
(Prettier can be integrated into most code editors, so that automatic style formatting can be integrated into the workflow as early as possible).

Updates README.md to include the information listed in this PR.

### CODE REVIEW

**Review by craigsweaton — APPROVED** [review]
Looks good to me. Plus it gives me the excuse to install the prettier plugin for VSCode

**Comment by 8thDay** [comment]
@Fixy250185 I've just set up Prettier on Sublime, so that it formats everything when I save a file... so far, I'm wondering how I lived without it!
(Bet it drives the "no semi-colon" people nuts though!)

**Comment by mairamartinsk** [comment]
@8thDay I've been using Prettier on Atom for some time now. It's brilliant!

**Review by mairamartinsk — APPROVED** [review]
Looks good. Changes are due to Prettier formatting rules.

**Pull request merged**
