### PR TITLE
Added react-router

### PR DESCRIPTION
**Pull request by craigsweaton**
I've added react-router along with the routes and components for the signup and login pages specified in the design. There is a new command you will need to run in order to install react-router locally, it is detailed in the readme.

### CODE REVIEW

**Review by 8thDay — COMMENTED** [review]
I notice that the components you've added are all classes, do they need to be? Could any of them be functions? 
https://reactarmory.com/answers/es6-classes-vs-function-components

**Comment by craigsweaton** [comment]
You mean functional stateless components? Depends if any of them need any state. The main page would certainly fit that, the others might too. Maybe only the profile page could be a class

**Comment by 8thDay** [comment]
Yes, that's what I had in mind 👍

I don't have a clear idea of which components will need any state, but it's worth bearing in mind, as we continue to develop the code.

**Review by GarrusNapp — DISMISSED** [review]
I think we can merge it. Class based components can be changed to FSC later, if needed.

**Comment by craigsweaton** [comment]
I've switched the Main, LogIn and SignUp components over to FSCs

**Review by 8thDay — APPROVED** [review]
Thank you for making the changes. 👍 
I realise that, as @GarrusNapp points out, class based components can be changed to FSC later, if needed. But it is my hope that raising the issue here, early in development, will get us thinking about, and discussing, best practices.

**Pull request merged**
